#!/bin/bash


# Script variables

WORKING_DIR="beat-factory" #this directory will be created in /home/pi
BEAT_NAME=( metricbeat filebeat heartbeat ) #metricbeat filebeat packetbeat auditbeat heartbeat
DOWNLOAD_PATH=""https://www.dropbox.com/s/0dpydq4sj0luaoa/beat-factory.zip?dl=1""
 # The path top the pre-compiled easyBeats - if downloaded from dropbox dl=1 is mendatory to create a direct 
LOG_PATH="/var/log"
LOG_DIR_NAME="wander"
WANDERFUL_BACKEND_DIR="$HOME/WanderfullController"
BRANCH_NAME="logging"


#functions:

function create_log_dirs {

	echo "Setting full permissions on parent log dir"
	chmod -R 777 "${LOG_PATH}"
	
	echo "Creating a log directory for wander"
	mkdir ${LOG_PATH}/${LOG_DIR_NAME}
}

function install_deps {
	apt-get install zip #install zip to uncompress the files
}

function download_and_unzip {
   # Download pre-compiled beat-factory
   wget -O ${HOME}/${WORKING_DIR}/ easyBeats.zip "${DOWNLOAD_PATH}"
   cd ${HOME}/${WORKING_DIR}/

   # Unzip the file
   unzip -o ${HOME}/${WORKING_DIR}/easyBeats.zip
}

function install_local {
  for beat in "${BEAT_NAME[@]}";
  do
    if [ ! -d /usr/share/$beat ];
    then
      echo "Creating /usr/share/$beat directory..."
       mkdir -p /usr/share/$beat/bin;
    fi

    if  [ ! -d /etc/$beat ];
    then
      echo "Creating /etc/$beat directory..."
       mkdir -p /etc/$beat;
    fi

    if [ ! -d /var/lib/$beat ];
    then
      echo "Creating /var/lib/$beat directory..."
       mkdir -p /var/lib/$beat
    fi

    echo "Installing $beat locally..."
     cp $HOME/${WORKING_DIR}/src/github.com/elastic/beats/${beat}/${beat} /usr/share/${beat}/bin
     cp $HOME/${WORKING_DIR}/src/github.com/elastic/beats/${beat}/${beat}.reference.yml /etc/${beat}
     cp $HOME/${WORKING_DIR}/src/github.com/elastic/beats/${beat}/${beat}.yml /etc/${beat}

    if [ $beat = "filebeat" ] || [ $beat = "metricbeat" ];
    then
       cp -R $HOME/${WORKING_DIR}/src/github.com/elastic/beats/${beat}/module /usr/share/${beat}
       cp -R $HOME/${WORKING_DIR}/src/github.com/elastic/beats/${beat}/modules.d/ /etc/${beat}
    fi

     cp $HOME/easyBEATS/services/${beat}.service /lib/systemd/system



     chmod -R 755 /etc/${beat}/;
     chown -R root:root /etc/${beat};
     chown -R root:root /usr/share/${beat}/*;
     /bin/systemctl daemon-reload;
     systemctl enable ${beat};
  done
}

function update_wander {
	echo "Entering wander directory: ${WANDERFUL_BACKEND_DIR}"
	cd ${WANDERFUL_BACKEND_DIR}
	
    echo "Fetching git branches"
	git fetch
	
	echo "Checking out branch: ${BRANCH_NAME}"
	git checkout ${BRANCH_NAME}
	
	echo "Pulling Git"
	git pull
}

function install_winston {
	cd ${HOME}
	npm install winston
}


#starting a progress:

echo "Creating a working directory for the script"
mkdir $HOME/${WORKING_DIR}/
   
echo "Creating log directory"
create_log_dirs

echo "Install dependencies"
install_deps

echo "Downloading the compressed directory"
download_and_unzip

echo "Installing on your local system..."
install_local

# TODO: get_the_new_version -
echo "Updating to new version with git"
update_wander

echo "Installing winston"
install_winston

# TODO: DELETE ALL

echo "Complete"
